//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Replica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.Checkouts = new HashSet<Checkout>();
        }
    
        public int booking_id { get; set; }
        public int user_id { get; set; }
        public int place_id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public int no_of_adults { get; set; }
        public Nullable<int> no_of_children { get; set; }
        public Nullable<int> no_of_infants { get; set; }
        public bool pets_allowed { get; set; }
        public decimal total_cost { get; set; }
        public int booking_status { get; set; }
        public Nullable<int> tokens { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual Place Place1 { get; set; }
        public virtual Place Place2 { get; set; }
        public virtual Place Place3 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checkout> Checkouts { get; set; }
    }
}
