//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Replica.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReplicaAirbnbEntities1 : DbContext
    {
        public ReplicaAirbnbEntities1()
            : base("name=ReplicaAirbnbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Nearby> Nearbies { get; set; }
        public virtual DbSet<Photogallery> Photogalleries { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<PlaceService> PlaceServices { get; set; }
        public virtual DbSet<PlaceSubtype> PlaceSubtypes { get; set; }
        public virtual DbSet<Placetype> Placetypes { get; set; }
        public virtual DbSet<ReviewsAndRating> ReviewsAndRatings { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<CheckAvailability> CheckAvailabilities { get; set; }
        public virtual DbSet<Checkout> Checkouts { get; set; }
        public virtual DbSet<ViewHistory> ViewHistories { get; set; }
    }
}
