//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Replica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewsAndRating
    {
        public int review_id { get; set; }
        public int booking_id { get; set; }
        public int reviewer_id { get; set; }
        public Nullable<int> user_reviewee_id { get; set; }
        public Nullable<int> property_reviewee_id { get; set; }
        public Nullable<decimal> user_rating { get; set; }
        public Nullable<decimal> property_rating { get; set; }
        public string user_comment { get; set; }
        public string property_comment { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
